## Assignment
### Pradyumn Agarwal
### 2140327 - 5PME
**Date: 29-09-23**

In [2]:
import numpy as np
import sympy as sym

> WAP to find the following for the given matrix.<br>
  $\quad A = \begin{bmatrix}
                6 & 1  & 1\\
                4 & −2 & 5\\
                2 & 8  & 7
           \end{bmatrix}
  $
> 1. Inverse of the matrix A using Gauss - Elimination method.
> 2. Inverse of the matrix A using numpy.
> 3. Determinant of A and hence the adjoint of the matrix .

**Inverse Using Gauss - Elimination method**

In [3]:
A = np.matrix([[6, 1, 1],[4, -2, 5],[2, 8, 7]],float)

In [4]:
def redRowEchelon(mat):
    for i in range(min(mat.shape)):
        row = mat[i,:].A1
        if(row[i] == 0):
            continue;
        row = row/row[i];
        mat[i,:] = row
        for j in range(mat.shape[0]):
            if(j==i):
                continue;
            mat[j,:] = mat[j,:] - (mat[j,i]*row)
        #print(mat)
    return mat

def geInverse(A):
    mat = np.insert(arr=A,obj=A.shape[1],values=np.identity(A.shape[1]),axis=1)
    mat = redRowEchelon(mat)
    print(mat)
    return mat[:,A.shape[1]:];
geInverse(A)

[[ 1.          0.          0.          0.17647059 -0.00326797 -0.02287582]
 [ 0.          1.          0.          0.05882353 -0.13071895  0.08496732]
 [ 0.          0.          1.         -0.11764706  0.1503268   0.05228758]]


matrix([[ 0.17647059, -0.00326797, -0.02287582],
        [ 0.05882353, -0.13071895,  0.08496732],
        [-0.11764706,  0.1503268 ,  0.05228758]])

**Inverse using numpy**

In [5]:
A.I

matrix([[ 0.17647059, -0.00326797, -0.02287582],
        [ 0.05882353, -0.13071895,  0.08496732],
        [-0.11764706,  0.1503268 ,  0.05228758]])

In [6]:
determinant_A = np.linalg.det(A)
print("Determinant = ",determinant_A)
print("Adjoint - ");
determinant_A*A.I

Determinant =  -306.0
Adjoint - 


matrix([[-54.,   1.,   7.],
        [-18.,  40., -26.],
        [ 36., -46., -16.]])

> Given the system of linear equations.<br>
    $\quad \quad
    \begin{align}
		3x - 5y + 4z &= 5\\
		5x + 2y + z  &= 0\\
		2x + 3y - 2z &= 3
    \end{align}
    $<br>
> WAP to find the following.
    > 1. The eigenvalues and corresponding eigen vectors of the coefficient matrix.
    > 2. Solve the system of equations using Cramer’s rule and print the solution.
    > 3. Find the transpose of the coefficient matrix and hence the trace.

In [7]:
A = np.matrix([[3,-5,4],
               [5,2,1],
               [2,3,-2]])
B = np.matrix([[5],[0],[3]])
print("Coefficient Matrix")
print(A)
print("Constant Matrix")
print(B)

Coefficient Matrix
[[ 3 -5  4]
 [ 5  2  1]
 [ 2  3 -2]]
Constant Matrix
[[5]
 [0]
 [3]]


**Eigenvalues and Eigenvectors**

In [8]:

eigen = np.linalg.eig(A)
print("Eigenvalues = ",eigen[0])
print("Eigenvectors:")
print(eigen[1])

Eigenvalues =  [ 2.45481218+3.65368793j  2.45481218-3.65368793j -1.90962436+0.j        ]
Eigenvectors:
[[ 0.01569385-0.54750431j  0.01569385+0.54750431j -0.40422239+0.j        ]
 [-0.72490133+0.j         -0.72490133-0.j          0.29555775+0.j        ]
 [-0.40816322+0.08895828j -0.40816322-0.08895828j  0.86559221+0.j        ]]


**Solving using Cramers rule**

In [9]:
D = [];
for i in range(0,A.shape[0]):
    C = A.T.copy();
    C[i] = B.T;
    C = C.T;
    D.append(np.linalg.det(C))
D.append(np.linalg.det(A))
X = [D[i]/D[-1] for i in range(0,A.shape[0])]
print(X)

[1.9999999999999996, -3.0, -3.999999999999999]


**Transpose and Trace**

In [10]:
print("Transpose of Matrix: ")
print(A.T)

print("Trace of Matrix: ")
print(np.trace(A))

Transpose of Matrix: 
[[ 3  5  2]
 [-5  2  3]
 [ 4  1 -2]]
Trace of Matrix: 
3


> WAP to find the rank of $P+Q$ <br>
$
\quad \quad
P = \begin{bmatrix}
          1 &1 &−1\\
          2 &−3& 4\\
          3 &−2& 3
     \end{bmatrix}
\quad
Q = \begin{bmatrix}
         −1 &−2 &−1\\
          6 &12 &6\\
          5 &10 &5
     \end{bmatrix}
$


In [11]:
def rowEchelon(A):
    mat = A.copy()
    for i in range(min(mat.shape)):
        row = mat[i,:].A1
        if(row[i] == 0):
            continue;
        row = row/row[i];
        mat[i,:] = row
        for j in range(i+1,mat.shape[0]):
            mat[j,:] = mat[j,:] - (mat[j,i]*row)
        #print(mat)
    return mat

def getRank(mat):
    flag = ~rowEchelon(mat).astype(bool).A
    rem = []
    #flag = np.delete(flag,next((i for i in range(len(flag)) if(flag[i].all())),[]),0)
    for i in range(len(flag)):
        if i in rem:
            continue;
        for j in range(i+1,len(flag)):
            if j in rem:
                continue;
            if((flag[i]==flag[j]).all() or flag[j].all()):
                rem.append(j)
    flag = np.delete(flag,rem,0)
    return len(flag)
P = np.matrix([
    [1, 1, -1],
    [2, -3, 4],
    [3, -2, 3]])
Q = np.matrix([
    [-1, -2, -1],
    [6, 12, 6],
    [5, 10, 5]])
print("Rank = ",getRank(P+Q))

Rank =  1


> WAP to find the nullity of the matrix B.<br>
$
\quad \quad
B = \begin{bmatrix}
        0 & 1 & 0 & 0 & 0 \\
        1 & 0 & 0 & 0 & 0 \\
        0 & 0 & 0 & 0 & 0
     \end{bmatrix}
$


In [18]:
B = np.matrix([
    [0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0]])
print("Nullity =",B.shape[0] - getRank(B))

Nullity = 1


> WAP to prove rank - nullity theorem of the matrix C.<br>
$
\quad \quad
C = \begin{bmatrix}
        1 &2 &13\\
        4 &−5& 6\\
        −7& 18& 9
     \end{bmatrix}
$


In [52]:
C = np.matrix([
    [1,2 ,13],
    [4 ,-5, 6],
    [-7 ,18,9]])
rank = getRank(C)
dim = C.shape[0]
nullSpace = np.linalg.solve(C,np.zeros((C.shape[1],1)))
print("Rank = ",rank)
print("Dimension =",dim)

print("Nullity = ",nullSpace.shape[1] - 1)
print((rank + nullSpace.shape[1] - 1 == dim))

Rank =  3
Dimension = 3
Nullity =  0
True
