## Assignment
### Pradyumn Agarwal
### 2140327 - 5PME
**Date: 26-09-23**

In [23]:
import numpy as np
import sympy as sym

> The theatre department of Christ University sold three kinds of tickets to its latest production of Macbeth. The faculty tickets sold for INR 75, the postgraduate student tickets for INR 50 and the undergraduate tickets for INR 40. The theatre department sold 250 tickets in total and brought in INR 14,125 in one night. The number of postgraduate student tickets sold was twice the number of faculty tickets sold. WAP to - <br>
> (a) Model the above situation using a system of equations. <br>
> (b) Write down the relevant Python codes for solving the above system of equations using the following methods:<br>
    1. Matrix Inverse method<br>
    2. Cramer’s rule

In [61]:
F,P,U = sym.symbols("F,P,U");
eq1 = sym.Eq(F + P + U,250);
eq2 = sym.Eq(75*F + 50*P + 40*U,14125);
eq3 = sym.Eq(-2*F + P,0)
print("F - Faculty     P - Postgraduate    U - Undergraduate");
print("The equations are- ")
sym.pprint(eq1)
sym.pprint(eq2)
sym.pprint(eq3)

print("Solution - ");
print(sym.solve([eq1,eq2,eq3]))

F - Faculty     P - Postgraduate    U - Undergraduate
The equations are- 
F + P + U = 250
75⋅F + 50⋅P + 40⋅U = 14125
-2⋅F + P = 0
Solution - 
{F: 75, P: 150, U: 25}


In [57]:
print("In Matrix form - ")
X = np.matrix([[F],[P],[U]]);
print("Variables - ");
print(X);
A = np.matrix([[1,1,1],[75,50,40],[-2,1,0]]);
B = np.matrix([[250],[14125],[0]]);
print("A = ");
print(A)
print("B = ");
print(B)


no_of_tickets = dict(zip(X.A1,((A.I)*B).A1))
print(no_of_tickets)

In Matrix form - 
Variables - 
[[F]
 [P]
 [U]]
A = 
[[ 1  1  1]
 [75 50 40]
 [-2  1  0]]
B = 
[[  250]
 [14125]
 [    0]]
{F: 74.99999999999994, P: 150.0000000000001, U: 25.0}


In [8]:
A = np.matrix([[1,1,2],[1,2,1],[2,7,8]])
A

matrix([[1, 1, 2],
        [1, 2, 1],
        [2, 7, 8]])

In [13]:
B = np.matrix([[1,1,2],[-1,0,-3],[0,5,0]])
B

matrix([[ 1,  1,  2],
        [-1,  0, -3],
        [ 0,  5,  0]])

> Equivalent Matrix

In [10]:
def rowEchelon(A):
    mat = A.copy()
    for i in range(min(mat.shape)):
        row = mat[i,:].A1
        if(row[i] == 0):
            continue;
        row = row/row[i];
        mat[i,:] = row
        for j in range(i+1,mat.shape[0]):
            mat[j,:] = mat[j,:] - (mat[j,i]*row)
    return mat

In [14]:
print("Equivalent Matrix of A: ");
rowEchelon(A)

Equivalent Matrix of A: 


matrix([[ 1,  1,  2],
        [ 0,  1, -1],
        [ 0,  0,  1]])

In [15]:
print("Equivalent Matrix of B: ");
rowEchelon(B)

Equivalent Matrix of B: 


matrix([[ 1,  1,  2],
        [ 0,  1, -1],
        [ 0,  0,  1]])

> Determinant and Adjoint

In [24]:
print("Determinant of A = ",int(np.linalg.det(A)));
print("Adjoint of A:");
A.I*np.linalg.det(A)

Determinant of A =  9
Adjoint of A:


matrix([[ 9.,  6., -3.],
        [-6.,  4.,  1.],
        [ 3., -5.,  1.]])

In [25]:
print("Determinant of B = ",int(np.linalg.det(B)));
print("Adjoint of B:");
B.I*np.linalg.det(B)

Determinant of B =  4
Adjoint of B:


matrix([[15., 10., -3.],
        [ 0.,  0.,  1.],
        [-5., -5.,  1.]])