## LAB 2: System of Equations

**Dates: 24-07-23 to 31-07-23**

**Row Echelon form of Matrix**<br>
>

In [2]:
import numpy as np

def rowEchelon(A):
    mat = A.copy()
    for i in range(min(mat.shape)):
        row = mat[i,:].A1
        if(row[i] == 0):
            continue;
        row = row/row[i];
        mat[i,:] = row
        for j in range(i+1,mat.shape[0]):
            mat[j,:] = mat[j,:] - (mat[j,i]*row)
        #print(mat)
    return mat

#myMat = np.matrix(eval(input("Enter Matrix:")),float);
#myMat = np.matrix([[-2,1,-3],[4,5,6],[-4,2,-6],[8,10,12]],float)
#myMat = np.matrix([[1,-1,2,2],[2,1,4,7],[4,-1,1,4]],float)
#myMat = np.matrix([[2,5,9,2],[4,8,6,3],[5,-4,6,5],[3,9,7,7]],float)
myMat = np.matrix([[1,1,-1,7],[1,-1,2,3],[2,1,1,9]],float)

print("Matrix: ")
print(myMat)
print("Row Echelon Form: ")
print(rowEchelon(myMat))

Matrix: 
[[ 1.  1. -1.  7.]
 [ 1. -1.  2.  3.]
 [ 2.  1.  1.  9.]]
Row Echelon Form: 
[[ 1.   1.  -1.   7. ]
 [-0.   1.  -1.5  2. ]
 [ 0.   0.   1.  -2. ]]


**Rank of a matrix**<br>
>

In [3]:
def getRank(mat):
    flag = ~rowEchelon(mat).astype(bool).A
    rem = []
    #flag = np.delete(flag,next((i for i in range(len(flag)) if(flag[i].all())),[]),0)
    for i in range(len(flag)):
        if i in rem:
            continue;
        for j in range(i+1,len(flag)):
            if j in rem:
                continue;
            if((flag[i]==flag[j]).all() or flag[j].all()):
                rem.append(j)
    flag = np.delete(flag,rem,0)
    return len(flag)

#myMat = np.matrix(eval(input("Enter Matrix:")),float);
myMat = np.matrix([[-2,1,-3],[4,5,6],[-4,2,-6],[8,10,12]],float)
print("Matrix: ")
print(myMat)
print("Rank = ",getRank(myMat))

Matrix: 
[[-2.  1. -3.]
 [ 4.  5.  6.]
 [-4.  2. -6.]
 [ 8. 10. 12.]]
Rank =  2


In [4]:
#Using linalg
import numpy as np

#myMat = np.matrix(eval(input("Enter Matrix:")));
myMat = np.matrix([[-2,1,-3],[4,5,6],[-4,2,-6],[8,10,12]],float)
rank = np.linalg.matrix_rank(myMat);
print("Rank = ",rank)

Rank =  2


**Gauss Elemination Method for System of Equations**<br>
> We have $\ldots\quad\quad\quad AX = B$<br>
  Then $\ldots \quad [A:B] = \begin{bmatrix}
              a_{11} & a_{12} & a_{13} & : & b_{1}\\
              a_{21} & a_{22} & a_{23} & : & b_{2}\\
              a_{31} & a_{32} & a_{33} & : & b_{3}
           \end{bmatrix}
  $
  $\quad\sim\quad \begin{bmatrix}
              a_{11} & a_{12} & a_{13} & : & b_{1}\\
                 0   & a_{22} & a_{23} & : & b_{2}\\
                 0   &   0    & a_{33} & : & b_{3}
           \end{bmatrix}
  $<br>
  Solve for $X$ using transformed $A$ and $B$

In [5]:
import numpy as np

def gaussMethod(A,B):
    mat = np.insert(arr=A,obj=A.shape[1],values=B.A1,axis=1)
    mat = rowEchelon(mat)
    print(mat)
    A_ = mat[:,:-1].A #Get Without Last Columns
    B_ = mat[:,-1:] #Get Last Column
    X = np.matrix(np.zeros(B.shape),float)
    varSolved = []
    solving = [list(i).count(0) for i in A_]
    for i in range(A_.shape[1])[::-1]:
        rowIndex = solving.index(i)
        row = A_[rowIndex,:]
        for j in range(A_.shape[1]):
            #print("rowele:",j,"    ",varSolved)
            if((row[j] != 0) and (j not in varSolved)):
                varSolved.append(j)
                break;
        #print(i,varSolved)
        X[varSolved[-1],0] = (B_[rowIndex,0] - np.sum([row[k]*X[k,0] for k in range(len(row))]))/row[varSolved[-1]]
    #X = np.linalg.solve(mat.T[:-1,:].T,mat.T[-1,:].T)
    return(X)
A = np.matrix([[2,5,9,2],[4,8,6,3],[5,-4,6,5],[3,9,7,7]],float)
#A = np.matrix([[1,-1,2],[2,1,4],[4,-1,1]],float)
B = np.matrix([[2],[7],[4],[1]],float)
#print(getRank(A))
print("Solved: \n",gaussMethod(A,B))
print("Solved: \n",np.linalg.solve(A,B))

[[ 1.          2.5         4.5         1.          1.        ]
 [-0.          1.          6.          0.5        -1.5       ]
 [ 0.          0.          1.          0.1        -0.31212121]
 [ 0.          0.          0.          1.         -0.95580808]]
Solved: 
 [[ 2.23737374]
 [ 0.27714646]
 [-0.2165404 ]
 [-0.95580808]]
Solved: 
 [[ 2.23737374]
 [ 0.27714646]
 [-0.2165404 ]
 [-0.95580808]]


**Reduced Row Echelon Form**<br>
>

In [13]:
import numpy as np

def redRowEchelon(mat):
    for i in range(min(mat.shape)):
        row = mat[i,:].A1
        if(row[i] == 0):
            continue;
        row = row/row[i];
        mat[i,:] = row
        for j in range(mat.shape[0]):
            if(j==i):
                continue;
            mat[j,:] = mat[j,:] - (mat[j,i]*row)
        #print(mat)
    return mat

#myMat = np.matrix(eval(input("Enter Matrix:")),float);
#myMat = np.matrix([[-2,1,-3],[4,5,6],[-4,2,-6],[8,10,12]],float)
#myMat = np.matrix([[1,-1,2,2],[2,1,4,7],[4,-1,1,4]],float)
#myMat = np.matrix([[2,5,9,2],[4,8,6,3],[5,-4,6,5],[3,9,7,7]],float)
myMat = np.matrix([[1,1,-1,7],[1,-1,2,3],[2,1,1,9]],float)

print("Matrix: ")
print(myMat)
print("Reduced Row Echelon Form: ")
print(redRowEchelon(myMat))

Matrix: 
[[ 1.  1. -1.  7.]
 [ 1. -1.  2.  3.]
 [ 2.  1.  1.  9.]]
Reduced Row Echelon Form: 
[[ 1.  0.  0.  6.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -2.]]


**Gauss Jordan Method for System of Equations**<br>
> We have $\ldots\quad\quad\quad AX = B$<br>
  Then $\ldots \quad [A:B] = \begin{bmatrix}
              a_{11} & a_{12} & a_{13} & : & b_{1}\\
              a_{21} & a_{22} & a_{23} & : & b_{2}\\
              a_{31} & a_{32} & a_{33} & : & b_{3}
           \end{bmatrix}
  $
  $\quad\sim\quad \begin{bmatrix}
              a_{11} &   0    &   0    & : & b_{1}\\
                 0   & a_{22} &   0    & : & b_{2}\\
                 0   &   0    & a_{33} & : & b_{3}
           \end{bmatrix}
  $<br>
  Solve for $X$ using transformed $A$ and $B$

In [14]:
def gaussJordanMethod(A,B):
    mat = np.insert(arr=A,obj=A.shape[1],values=B.A1,axis=1)
    mat = redRowEchelon(mat)
    print(mat)
    A_ = mat.T[:-1,:].T.A
    B_ = mat.T[-1,:].T
    return B_
#A = np.matrix([[2,5,9,2],[4,8,6,3],[5,-4,6,5],[3,9,7,7]],float)
#A = np.matrix([[1,-1,2],[2,1,4],[4,-1,1]],float)
#B = np.matrix([[2],[7],[4],[1]],float)
A = np.matrix([[1,1,-1],[1,-1,2],[2,1,1]],float)
B = np.matrix([[7],[3],[9]],float)
#print(getRank(A))
print("Solved: \n",gaussJordanMethod(A,B))
print("Solved: \n",np.linalg.solve(A,B))

[[ 1.  0.  0.  6.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1. -2.]]
Solved: 
 [[ 6.]
 [-1.]
 [-2.]]
Solved: 
 [[ 6.]
 [-1.]
 [-2.]]


**Inverse Using Gauss Jordan Method**

In [41]:
import numpy as np
def gjInverse(A):
    mat = np.insert(arr=A,obj=A.shape[1],values=np.identity(A.shape[1]),axis=1)
    mat = redRowEchelon(mat)
    print(mat)
    return mat[:,A.shape[1]:];

A = np.matrix([[1,-1,2],[2,1,4],[4,-1,1]],float)
gjInverse(A)

[[ 1.          0.          0.         -0.23809524  0.04761905  0.28571429]
 [ 0.          1.          0.         -0.66666667  0.33333333  0.        ]
 [-0.         -0.          1.          0.28571429  0.14285714 -0.14285714]]


matrix([[-0.23809524,  0.04761905,  0.28571429],
        [-0.66666667,  0.33333333,  0.        ],
        [ 0.28571429,  0.14285714, -0.14285714]])