## MID SEM EXAMINATION
### Pradyumn Agarwal
### 2140327 - 5PME
**Date: 04-10-23**

In [9]:
import numpy as np
import sympy as sym

In [10]:
# Q3

In [47]:
#F @ 21
#P @ 27
#U @ 27

# Total Tickets = 40
# Total INR = 2140327
# P = 2F

#F + P + U = 40
#21*F + 27*P +27*U = 2140327
#2F - P = 0

In [48]:
F,P,U = sym.symbols("F,P,U")

eq1 = sym.Eq(F + P + U, 40)
eq2 = sym.Eq(21*F + 27*P +27*U, 2140327)
eq3 = sym.Eq(2*F - P, 0)

In [49]:
print("The Equations are- ")

The Equations are- 


In [50]:
eq1

Eq(F + P + U, 40)

In [51]:
eq2

Eq(21*F + 27*P + 27*U, 2140327)

In [52]:
eq3

Eq(2*F - P, 0)

In [53]:
sym.solve([eq1,eq2,eq3])

{F: -2139247/6, P: -2139247/3, U: 2139327/2}

In [54]:
#SOLVING WITH MATRIX INVERSE METHOD

In [55]:
A = np.matrix([[1,1,1],
               [21,27,27],
               [2,-1,0]])
X = np.matrix([[F],[P],[U]])
B = np.matrix([[40],[2140327],[0]])
print(A)
if(np.linalg.det(A) == 0):
    print("NOT POSSIBLE");
else:
    X_ = (A.I)*B
    print("Solution for number of tickets is -")
    print(dict(zip(X.A1,X_.A1)))

[[ 1  1  1]
 [21 27 27]
 [ 2 -1  0]]
Solution for number of tickets is -
{F: -356541.1666666668, P: -713082.3333333336, U: 1069663.5000000005}


In [56]:
#SOLVING WITH CRAMERS RULE

In [57]:
A = np.matrix([[1,1,1],
               [21,27,27],
               [2,-1,0]])
B = np.matrix([[40],[2140327],[0]])
X = np.matrix([[F],[P],[U]])
D = []
for i in range(0,A.shape[0]):
    C = (A.T).copy()
    C[i] = B.T
    C = C.T
    D.append(np.linalg.det(C))
D.append(np.linalg.det(A));
SOL = [D[i]/D[-1] for i in range(len(D)-1)]
print("Solution for number of tickets is -")
print(dict(zip(X.A1,SOL)))

Solution for number of tickets is -
{F: -356541.1666666669, P: -713082.333333334, U: 1069663.5000000005}


In [58]:
# Q4

In [59]:
A = np.matrix([[1,1,2],
               [1,2,1],
               [2,7,8]])
A

matrix([[1, 1, 2],
        [1, 2, 1],
        [2, 7, 8]])

In [81]:
B = np.matrix([[1,1,2],
               [-1,0,-3],
               [0,5,0]])
B

matrix([[ 1,  1,  2],
        [-1,  0, -3],
        [ 0,  5,  0]])

In [82]:
# (a)
print("Equivalent Matrix is -")
for i in range(B.shape[0]):
    if(B[i,i] == 0):
        continue;
    B[i] = B[i]/B[i,i];
    for j in range(i+1,B.shape[1]):
        B[j] = B[j] - B[j,i]*B[i] 
B

Equivalent Matrix is -


matrix([[ 1,  1,  2],
        [ 0,  1, -1],
        [ 0,  0,  1]])

In [63]:
# (b)

det_A = np.linalg.det(A)
print("Determinant of A = ",det_A)

adj_A = det_A*(A.I)
print("Adjoint Matrix -")
print(adj_A)

Determinant of A =  9.000000000000002
Adjoint Matrix -
[[ 9.  6. -3.]
 [-6.  4.  1.]
 [ 3. -5.  1.]]
