## LAB 5: LU Decomposition

**Date: 10-02-2024, 10-02-2024**

In [1]:
import numpy as np
from typing import *

In [2]:
# FROM MAT551_LA2
def rowEchelon(A):
    mat = A.copy()
    for i in range(min(mat.shape)):
        row = mat[i,:].A1
        if(row[i] == 0):
            continue;
        row = row/row[i];
        mat[i,:] = row
        for j in range(i+1,mat.shape[0]):
            mat[j,:] = mat[j,:] - (mat[j,i]*row)
        #print(mat)
    return mat

#def redRowEchelon(mat):
#    for i in range(min(mat.shape)):
#        row = mat[i,:].A1
#        if(row[i] == 0):
#            continue;
#        row = row/row[i];
#        mat[i,:] = row
#        for j in range(mat.shape[0]):
#            if(j==i):
#                continue;
#            mat[j,:] = mat[j,:] - (mat[j,i]*row)
#        #print(mat)
#    return mat

In [3]:
def decompose(A:"np.matrix"):
    # Assert A is Square Matrix
    assert A.shape[0] == A.shape[1]
    
    n = A.shape[0]
    L,U = np.diag([1.00]*len(A)),A.copy();
    
    for i in range(n):
        #row = U[i,:].A1
        if(U[i,i] == 0):
            continue;
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i]
            U[j,:] = U[j,:] - U[i,:]*(U[j,i]/U[i,i])    
    return np.matrix(L),np.matrix(U),(L*U == A).all()

def LUsolve(A:"np.matrix",B:"np.matrix"):
    assert A.shape[0] == B.shape[0]
    
    L,U,f = decompose(A)
    #return np.linalg.solve(U,np.linalg.solve(L,B)) if(f) else False
    return U.I*(L.I * B) if(f) else False

In [4]:
A = np.matrix([[1,1,1],[4,3,-1],[3,-5,3]], dtype=float)
B = np.matrix([1,6,4],dtype=float).T

decompose(A)

(matrix([[1., 0., 0.],
         [4., 1., 0.],
         [3., 8., 1.]]),
 matrix([[ 1.,  1.,  1.],
         [ 0., -1., -5.],
         [ 0.,  0., 40.]]),
 True)

In [5]:
LUsolve(A,B)

matrix([[ 1.5  ],
        [-0.125],
        [-0.375]])

In [6]:
np.linalg.solve(A,B)

matrix([[ 1.5  ],
        [-0.125],
        [-0.375]])

In [7]:
A = np.matrix([[2,-1,-2],[-4,6,3],[-4,-2,8]], dtype= float)
#A = np.matrix([[4,3,6],[-1,3,2],[-4,9,7]], dtype= float)
B = np.matrix([1,1,1],dtype=float).T

LUsolve(A,B)

matrix([[3.125],
        [1.25 ],
        [2.   ]])

In [8]:
np.linalg.solve(A,B)

matrix([[3.125],
        [1.25 ],
        [2.   ]])

**Date: 19-02-24**

> WAP to solve the following system of equations using LU decomposition.<br>
> $\quad  2x - y - 2z = 9$<br>
> $\quad -4x + 6y + 3z = 8$<br>
> $\quad -4x - 2y + 8z = 10$

In [9]:
A = np.matrix([[2,-1,-2],[-4,6,3],[-4,-2,8]], dtype= float)
B = np.matrix([9,8,10],dtype=float).T

LUsolve(A,B)

matrix([[28.],
        [11.],
        [18.]])

In [10]:
np.linalg.solve(A,B)

matrix([[28.],
        [11.],
        [18.]])

**Date: 20-02-24**

> WAP to check if every matrix has LU decomposition

In [18]:
#SINGULAR MATRIX
A = np.matrix([[1,2,2],[2,4,4],[7,8,9]])
L,U,f = decompose(A)
f,(L*U == A).all()

(True, True)

In [25]:
#IDENTITY MATRIX
A = np.identity(4)
L,U,f = decompose(A)
f,(L*U == A).all()

(True, True)

In [26]:
# MATRIX WITH 0 ELEMENT
A = np.matrix([[0,2,3],[4,5,6],[7,8,9]])
L,U,f = decompose(A)
f,(L*U == A)

(False,
 matrix([[ True,  True,  True],
         [ True,  True,  True],
         [False,  True, False]]))

In [31]:
A = np.matrix([[2,5,3],[5,2,6],[9,3,7]])
L,U,f = decompose(A)
f,(L*U == A)

(False,
 matrix([[ True,  True,  True],
         [ True, False, False],
         [ True, False, False]]))

In [32]:
A = np.matrix([[1,2,3],[2,4,5],[1,3,4]])
L,U,f = decompose(A)
f,(L*U == A).all()

(True, True)

In [35]:
A = np.matrix([[2,2,3],[5,5,6],[9,3,7]])
L,U,f = decompose(A)
f,(L*U == A)

(False,
 matrix([[ True,  True,  True],
         [ True,  True, False],
         [ True,  True, False]]))

In [40]:
A = np.matrix([[0,2,3],[2,5,6],[5,3,7]])
L,U,f = decompose(A)
f,(L*U == A)

(False,
 matrix([[ True,  True,  True],
         [ True,  True,  True],
         [False,  True, False]]))

In [41]:
A = np.matrix([[0,2],[2,2]])
L,U,f = decompose(A)
f,(L*U == A)

(True,
 matrix([[ True,  True],
         [ True,  True]]))