## LAB 1: Revision

**Date: 19-12-2023**

In [3]:
import numpy as np

> WAP to solve the following system of linear equations: <br>
    $
        \quad 2x - y + 3z = 8 \\
        \quad  x +2y +  z = 7 \\
        \quad 3x + y - 2x = 9
    $

In [7]:
A = np.matrix([[2,-1,8],
               [1,2,1],
               [3,1,-2]])
B = np.matrix([8,7,9]).T

print(A.I * B)

[[2.74545455]
 [1.85454545]
 [0.54545455]]


> WAP to find the roots of the given quadratic equation:<br>
    $\quad x^{2} + x + 1 = 0$

In [25]:
P = np.array([1,1,1])
print(np.roots(P))

[-0.5+0.8660254j -0.5-0.8660254j]


> WAP to display 10 values between 0 and 10 including 10.

In [18]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

> WAP to display 10 values between 0 and 10 excluding 10.

In [19]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

> WAP to add and multiply two matrices.

In [21]:
A = np.matrix(eval(input("Enter First Matrix:")))
B = np.matrix(eval(input("Enter Second Matrix:")))

print("SUM = ")
print(A+B)
print("PRODUCT = ")
print(A*B)

Enter First Matrix:[[1,4],[5,9]]
Enter Second Matrix:[[-2,4],[3,6]]
SUM = 
[[-1  8]
 [ 8 15]]
PRODUCT = 
[[10 28]
 [17 74]]


> WAP to find the invese of a matrix

In [22]:
A = np.matrix(eval(input("Enter First Matrix:")))
print("Invese = ")
print(A.I)

Enter First Matrix:[[1,4],[5,9]]
Invese = 
[[-0.81818182  0.36363636]
 [ 0.45454545 -0.09090909]]
